-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
